let langdataIndex = {
    "languages": {
        "es": {
            "strings": {
                "nav-about-me": "Sobre mí",
                "nav-proyects": "Proyectos",
                "nav-education": "Educación",
                "nav-experience": "Experiencia",
                "nav-awards": "Premios",

                "desc-title": "¡Bienvenid@!",
                "desc-abstract": "Mi nombre es Cristóbal Allendes, y soy un estudiante de Ingeniería Civil Eléctrica en la Universidad de Chile. Estoy interesado en las áreas de procesamiento de señales e imágenes, machine learning, robótica y electrónica, y me gusta el trabajo tanto con software como hardware.",
                "desc-about-me-title": "Sobre mí",
                "desc-about-me-p1": "Mi mayor pasión es aprender de distintos temas, en especial cuando los puedo vincular de vuelta a la ingeniería eléctrica: desde las matemáticas puras y aplicadas a la física y astronomía, pasando por áreas como la ingeniería mecánica y el desarrollo de software.",
                "desc-about-me-p2": "Mis hobbies son la programación, la música y los videojuegos, y me encanta cuando puedo relacionarlos con mi área de estudio. Por esto me he interesado en proyectos como la creación de software de análisis de señales, que me permiten vincular la programación con el procesamiento de señales, e incluso he podido involucrar a la música a través de la implementación de sintetizadores con este software.",

                "proy-title": "Proyectos",
                "proy-p1-title": "Test 1 title",
                "proy-p1-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Est ante in nibh mauris cursus. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Maecenas accumsan lacus vel facilisis volutpat.",
                "proy-p1-link": "Test 1 link",
                "proy-p2-title": "Test 2 title",
                "proy-p2-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Est ante in nibh mauris cursus. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Maecenas accumsan lacus vel facilisis volutpat.",
                "proy-p2-link": "Test 2 link",
                "proy-p3-title": "Small title",
                "proy-p3-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                "proy-p3-link": "Small link",

                "ed-title": "Educación",
                "ed-e1-title": "Ingeniería Civil Eléctrica",
                "ed-e1-date": "Marzo 2019 - presente",
                "ed-e1-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Est ante in nibh mauris cursus. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Maecenas accumsan lacus vel facilisis volutpat.",
                "ed-e2-title": "Test",
                "ed-e2-date": "Marzo 2019 - presente",
                "ed-e2-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Est ante in nibh mauris cursus. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Maecenas accumsan lacus vel facilisis volutpat.",
                "ed-e3-title": "Longer title",
                "ed-e3-date": "Marzo 2019 - presente",
                "ed-e3-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Est ante in nibh mauris cursus. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Maecenas accumsan lacus vel facilisis volutpat.",

                "exp-title": "Experiencia",
                "exp-e1-title": "Test 1",
                "exp-e1-date": "Marzo 2019",
                "exp-e1-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Est ante in nibh mauris cursus. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Maecenas accumsan lacus vel facilisis volutpat.",
                "exp-e2-title": "Test",
                "exp-e2-date": "Marzo 2019",
                "exp-e2-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Est ante in nibh mauris cursus. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Maecenas accumsan lacus vel facilisis volutpat.",
                "exp-e3-title": "Longer title",
                "exp-e3-date": "Marzo 2019",
                "exp-e3-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Est ante in nibh mauris cursus. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Maecenas accumsan lacus vel facilisis volutpat.",

                "aw-title": "Premios",
                "aw-e1-title": "Test 1",
                "aw-e1-date": "Marzo 2019",
                "aw-e1-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Est ante in nibh mauris cursus. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Maecenas accumsan lacus vel facilisis volutpat.",
                "aw-e2-title": "Test",
                "aw-e2-date": "Marzo 2019",
                "aw-e2-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Est ante in nibh mauris cursus. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Maecenas accumsan lacus vel facilisis volutpat.",
                "aw-e3-title": "Longer title",
                "aw-e3-date": "Marzo 2019",
                "aw-e3-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Est ante in nibh mauris cursus. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Maecenas accumsan lacus vel facilisis volutpat.",
            },
        },
        "en": {
            "strings": {
                "nav-about-me": "About me",
                "nav-proyects": "Proyects",
                "nav-education": "Education",
                "nav-experience": "Experience",
                "nav-awards": "Awards",

                "desc-title": "Welcome!",
                "desc-abstract": "My name is Cristóbal Allendes, and I am a Civil Electrical Engineering Student at Universidad de Chile. I am interested in the areas of signal and image processing, machine learning, robotics and electronics, and I enjoy working with both software and hardware.",
                "desc-about-me-title": "About me",
                "desc-about-me-p1": "My biggest passion is learning about different topics, especially when I can link them back to electrical engineering: from pure and applied mathematics, to physics and astronomy, including disciplines such as mechanical engineering and software development.",
                "desc-about-me-p2": "My hobbies are programming, music and videogames, and I love when I can relate them to my field of study. For this reason I have developed an interest in proyects such as the creation of signal processing software, which allows me to link programming with signal analysis, and I have even been able to involve music through the implementation of synthesizers using this software.",

                "proy-title": "Proyects",
                "proy-p1-title": "Test 1 title",
                "proy-p1-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Est ante in nibh mauris cursus. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Maecenas accumsan lacus vel facilisis volutpat.",
                "proy-p1-link": "Test 1 link",
                "proy-p2-title": "Test 2 title",
                "proy-p2-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Est ante in nibh mauris cursus. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Maecenas accumsan lacus vel facilisis volutpat.",
                "proy-p2-link": "Test 2 link",
                "proy-p3-title": "Small title",
                "proy-p3-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                "proy-p3-link": "Small link",

                "ed-title": "Education",
                "ed-e1-title": "Civil Electrical Engineering",
                "ed-e1-date": "March 2019 - current",
                "ed-e1-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Est ante in nibh mauris cursus. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Maecenas accumsan lacus vel facilisis volutpat.",
                "ed-e2-title": "Test",
                "ed-e2-date": "March 2019 - current",
                "ed-e2-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Est ante in nibh mauris cursus. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Maecenas accumsan lacus vel facilisis volutpat.",
                "ed-e3-title": "Longer title",
                "ed-e3-date": "March 2019 - current",
                "ed-e3-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Est ante in nibh mauris cursus. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Maecenas accumsan lacus vel facilisis volutpat.",

                "exp-title": "Experience",
                "exp-e1-title": "Test 1",
                "exp-e1-date": "March 2019",
                "exp-e1-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Est ante in nibh mauris cursus. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Maecenas accumsan lacus vel facilisis volutpat.",
                "exp-e2-title": "Test",
                "exp-e2-date": "March 2019",
                "exp-e2-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Est ante in nibh mauris cursus. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Maecenas accumsan lacus vel facilisis volutpat.",
                "exp-e3-title": "Longer title",
                "exp-e3-date": "March 2019",
                "exp-e3-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Est ante in nibh mauris cursus. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Maecenas accumsan lacus vel facilisis volutpat.",

                "aw-title": "Awards",
                "aw-e1-title": "Test 1",
                "aw-e1-date": "March 2019",
                "aw-e1-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Est ante in nibh mauris cursus. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Maecenas accumsan lacus vel facilisis volutpat.",
                "aw-e2-title": "Test",
                "aw-e2-date": "March 2019",
                "aw-e2-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Est ante in nibh mauris cursus. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Maecenas accumsan lacus vel facilisis volutpat.",
                "aw-e3-title": "Longer title",
                "aw-e3-date": "March 2019",
                "aw-e3-desc": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Feugiat in ante metus dictum at tempor commodo ullamcorper a. Est ante in nibh mauris cursus. Diam phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Maecenas accumsan lacus vel facilisis volutpat.",
            },
        },
    },
}

let langdataSignpy = {
    "languages": {
        "es": {
            "strings": {
                "nav-p-title": "Inicio",
                "proy-title": "SignPy",
                "proy-short-desc": "Software de procesamiento digital de señales"
            },
        },
        "en": {
            "strings": {
                "nav-p-title": "Home",
                "proy-title": "SignPy",
                "proy-short-desc": "Digital signal processing software"
            },
        },
    },
}